name: Deploy to Server

on:
  push:
    branches: [app]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: app

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Clear destination directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /usr/share/nginx/html/163-music

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/usr/share/nginx/html/163-music"
          strip_components: 1